name: DOCS

on:
  push:
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze', 'flake.nix', 'flake.lock') }}-documentation
      - name: build the docs
        run: |
          nix develop .#ci --command bash -c '
            cabal update
            cabal haddock \
              --haddock-hyperlink-source \
              --haddock-quickjump \
              --haddock-html-location="https://hackage.haskell.org/package/$pkg-$version/docs" \
              graft
            mkdir -p docs
            cp -rf dist-newstyle/build/*/ghc-*/graft-*/doc/html/graft/* docs
          '
      - name: upload docs as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: ./docs
      - name: deploy docs to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
